# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{vox-statsd-client}
  s.version = "0.1.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Pablo Mercado"]
  s.date = %q{2012-05-8}
  s.default_executable = %q{statsd-send}
  s.description = %q{A Ruby client for statsd - modified/recycled from https://github.com/dawanda/statsd-client}
  s.email = %q{pablo@voxmedia.com}
  s.executables = ["statsd-send"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "bin/statsd-send",
    "vox-statsd-client.gemspec",
    "lib/vox/statsd/client.rb",
    "statsd-client.example.yml"
  ]
  s.homepage = %q{http://github.com/vox/statsd-client}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Client for statds}

  if s.respond_to? :specification_version then
    s.specification_version = 3
    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
  end
end

